# Generated by Django 5.2.5 on 2025-08-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('repository_url', models.URLField()),
                ('root_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('synonims', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('code', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('subtext', models.TextField(blank=True, null=True)),
                ('code_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='api.codeasset')),
                ('technologies', models.ManyToManyField(blank=True, related_name='code_snippets', to='api.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.codesnippet')),
            ],
        ),
        migrations.AddField(
            model_name='codeasset',
            name='technologies',
            field=models.ManyToManyField(related_name='code_assets', to='api.technology'),
        ),
    ]
