# Generated by Django 5.2.5 on 2025-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.URLField()),
                ('file_path', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
